### ISSUE TITLE
Cluster rejoin fail

### ISSUE THREAD

**Issue by radut** [ekino/docker-neo4j-cluster#5]
Hi,
I have started up the cluster just fine,
but i killed a instance
then started, and it doesn't join the cluster.

==> Starting Neo4J server (with supervisord)

/usr/lib/python2.7/dist-packages/supervisor/options.py:295: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
2016-06-16 09:33:04,545 CRIT Supervisor running as root (no user in config file)
2016-06-16 09:33:04,545 WARN Included extra file "/etc/supervisor/conf.d/neo4j.conf" during parsing
Unlinking stale socket /var/run/supervisor.sock
2016-06-16 09:33:04,858 INFO RPC interface 'supervisor' initialized
2016-06-16 09:33:04,858 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2016-06-16 09:33:04,859 INFO supervisord started with pid 31
2016-06-16 09:33:05,860 INFO spawned: 'neo4j' with pid 34
2016-06-16 09:33:07,378 INFO exited: neo4j (exit status 1; not expected)
2016-06-16 09:33:08,380 INFO spawned: 'neo4j' with pid 166
2016-06-16 09:33:09,888 INFO exited: neo4j (exit status 1; not expected)
2016-06-16 09:33:11,891 INFO spawned: 'neo4j' with pid 298
2016-06-16 09:33:13,424 INFO exited: neo4j (exit status 1; not expected)
2016-06-16 09:33:16,428 INFO spawned: 'neo4j' with pid 430
2016-06-16 09:33:17,937 INFO exited: neo4j (exit status 1; not expected)
2016-06-16 09:33:18,938 INFO gave up: neo4j entered FATAL state, too many start retries too quickly

**Comment by radut** [comment]
More Info

Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.cluster.client.ClusterJoin@506622fe' was successfully initialized, but failed to start. Please see attached cause exception.
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:462)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
    at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:111)
    at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.newFacade(GraphDatabaseFacadeFactory.java:139)
    ... 10 more
Caused by: org.neo4j.graphdb.config.InvalidSettingException: Bad value 'neo1:5001,neo2:5001,neo3:5001neo1:5001,neo2:5001,neo3:5001neo1:5001,neo2:5001,neo3:5001' for setting 'ha.initial_hosts': neo3:5001neo1:5001
    at org.neo4j.kernel.configuration.Settings$DefaultSetting.apply(Settings.java:921)
    at org.neo4j.kernel.configuration.Settings$DefaultSetting.apply(Settings.java:841)
    at org.neo4j.kernel.configuration.Config.get(Config.java:119)
    at org.neo4j.cluster.client.ClusterClientModule$5.getInitialHosts(ClusterClientModule.java:214)
    at org.neo4j.cluster.client.ClusterJoin.joinByConfig(ClusterJoin.java:126)
    at org.neo4j.cluster.client.ClusterJoin.start(ClusterJoin.java:90)
    at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:452)
    ... 14 more

**Comment by frntn** [comment]
This repo is obsolete and not maintained since early 2015.
It have been created before the official Neo4j docker images were released.
Please see https://github.com/neo4j/docker-neo4j for official images and support
